### ISSUE TITLE
Can't mount anything without breaking everything

### ISSUE THREAD

**Issue by Dids** [deepstreamIO/deepstream.io-docker#2]
The following sample doesn't work, because it can't find the config files, as it only creates an empty directory locally:

```
docker run -p 6020:6020 \
-v $(pwd)/conf:/etc/deepstream \
deepstreamio/deepstream.io:latest
```

If I populate the conf directory with valid configurations and enable a few plugins, it throws an error that it can't find any of the modules.

**Comment by Dids** [comment]
For example, in my config.yml, I'm defining the redis plugin, like this:

```
plugins:
  message:
    name: redis
    options:
      host: redis
      port: 6379
```

This throws the following:

```
Error: Cannot find module 'deepstream.io-msg-redis'
Trace
    at Command.action (nexe.js:267:15)
    at Command.listener (nexe.js:6458:8)
    at emitNone (events.js:86:13)
    at Command.emit (events.js:185:7)
    at Object.__dirname.7.../package.json (nexe.js:395:11)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
    at nexe.js:1:505
    at NativeModule.compile (bootstrap_node.js:502:7)
    at Function.NativeModule.require (bootstrap_node.js:443:18)
```

**Comment by PhillippOhlandt** [comment]
Hey, seems like your config sets wrong paths for the plugins and the logs.

**Comment by Dids** [comment]
@PhillippOhlandt Oh wow, thanks for the fast reply!

I'm using the sample configs from here, I guess they're not up to date then?
https://github.com/deepstreamIO/docker/tree/master/deepstream.io-complete-backend/conf

**Comment by PhillippOhlandt** [comment]
Yep, that are old ones. You can find some deepstream demos on my account. Copy the config from there and you are good.

**Comment by Dids** [comment]
That worked perfectly, thank you!

**Comment by jeffijoe** [comment]
I'm having the same issue but from what I can tell the config schema has not changed?

**Comment by PhillippOhlandt** [comment]
@jeffijoe Make sure you use the correct lib path.

**Comment by jeffijoe** [comment]
All I have done so far is mount `/etc/deepstream` to `/etc/deepstream` with a config.yml in it, what else do I need to do?

**Comment by PhillippOhlandt** [comment]
You need to have the right lib path defined in the config file. `/var/lib/deepstream`

**Comment by jeffijoe** [comment]
@PhillippOhlandt I can't find anything related to a lib path in the docs: https://deepstream.io/docs/server/configuration/

**Comment by PhillippOhlandt** [comment]
It's right in the config file. https://github.com/deepstreamIO/deepstream.io/blob/master/conf/config.yml#L9

**Comment by jeffijoe** [comment]
Thanks! So it's undocumented on the website then, cause there's no entry for `libDir`. I'll try this out, thanks again!
