### ISSUE TITLE
request: Build 2.2.2 and publish to hub.docker.com

### ISSUE THREAD

**Issue by ralphtheninja** [deepstreamIO/deepstream.io-docker#3]
I wasn't aware of this repository so posted an issue [here](https://github.com/deepstreamIO/deepstream.io/issues/671) for reference

**Comment by ralphtheninja** [comment]
I could submit a PR for this but I guess `2.2.2` needs to be pushed to centos repos so we can grab it using `yum`.

**Comment by PhillippOhlandt** [comment]
Hey, sorry. I wasn't aware of the new versions. I haven't been communicated anywhere. Will add the new versions tonight.

**Comment by PhillippOhlandt** [comment]
@ralphtheninja He, sorry for the delay. The images are building now.
