### ISSUE TITLE
publish 3.1.4

### ISSUE THREAD

**Issue by tzapu** [deepstreamIO/deepstream.io-docker#6]
hello, it would be wonderful if you could publish 3.1.4 due to this issue https://github.com/deepstreamIO/deepstream.io/issues/891#issuecomment-407920619

thanks

**Comment by yasserf** [comment]
will do!

**Comment by botzill** [comment]
Hi. Any updates o this? Would be really nice to have latest version on dockethub.

Thx!

**Comment by yasserf** [comment]
I completely missed this =(, published it now. Had published newer versions as well. Sorry this year was a little hectic but its all coming back into full steam again now.
